name: Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  check-syntax:
    name: PHP ${{ matrix.php-version }} Syntax
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.3"
          - "8.4"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: opcache
          coverage: none
          tools: none
      -
        name: Check syntax
        uses: mlocati/check-php-syntax@v1
        with:
          fail-on-warnings: true

  check-install:
    name: Install on Concrete ${{ matrix.ccm-version }}
    runs-on: ubuntu-latest
    container: ghcr.io/concrete5-community/docker5:${{ matrix.ccm-version }}
    strategy:
      matrix:
        ccm-version:
          - "9.0"
          - "9.3"
          - latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Prepare package
        run: ln -s "$GITHUB_WORKSPACE" /app/packages/migration_tool
      -
        name: Start services
        run: ccm-service start db
      -
        name: Core info
        run: sudo -u www-data /app/concrete/bin/concrete5 --ansi --no-interaction c5:info
      -
        name: Install package
        run: sudo -u www-data /app/concrete/bin/concrete5 --ansi --no-interaction c5:package:install migration_tool
